### PR TITLE
feat: disable preview mode

### PR DESCRIPTION
**Pull request by vlnevyhosteny**

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@vlnevyhosteny this doesn't appear to be working for me? https://share.getcloudapp.com/nOubk7Zp

Essentially, navigating to page_address/?preview=1 should show the draft version of the page - so if previewing is enabled, the page likely needs to build two versions, the main version and then the ?preview=1 version

eg:
```
if buttercms_preview != false and ?preview=1 passed at end of URL
     show draft version
else
     show published version
```

It looks like there are changes in the remote content being created when I run the github go command to build the content. (need to updated gitignore)

Also, the url for /landing-page/alternate-landing-page/, for example, doesn't generate anything. Not every single landing page will have every single component or have the components in the same order; components can be mixed and matched

**Comment by vlnevyhosteny** [comment]
> Essentially, navigating to page_address/?preview=1 should show the draft version of the page - so if previewing is enabled, the page likely needs to build two versions, the main version and then the ?preview=1 version

@ViolanteCodes Basically using query parameters with Hugo is not possible https://github.com/gohugoio/hugo/issues/5307 . At least without additional JS code. So I setup env variable in Netlify that enables preview mode. (https://github.com/ButterCMS/hugo-starter-buttercms/pull/22/files#diff-b80385df109d2e96812772e7905b6d846a851623b7261d35480bdb4e83a009d0R2)

Maybe there is solution that we can create structure like `/preview/landing-page/blabla` or `/preview/blog/post/blabla`. But it would double the structures in code.

**Comment by ViolanteCodes** [comment]
> > Essentially, navigating to page_address/?preview=1 should show the draft version of the page - so if previewing is enabled, the page likely needs to build two versions, the main version and then the ?preview=1 version
> 
> @ViolanteCodes Basically using query parameters with Hugo is not possible [gohugoio/hugo#5307](https://github.com/gohugoio/hugo/issues/5307) . At least without additional JS code. So I setup env variable in Netlify that enables preview mode. (https://github.com/ButterCMS/hugo-starter-buttercms/pull/22/files#diff-b80385df109d2e96812772e7905b6d846a851623b7261d35480bdb4e83a009d0R2)
> 
> Maybe there is solution that we can create structure like `/preview/landing-page/blabla` or `/preview/blog/post/blabla`. But it would double the structures in code.

@jakelumetta can you let me know if this is okay? It means the butter iframe for preview wouldn't work the same for hugo as all the other frameworks, but given that hugo doesn't support query params, not sure what else we can do?

**Comment by prokopsimek** [comment]
@ViolanteCodes Hi! This is the same issue as we had with GatsbyJS. Since all pages are generated before releasing to live environment, so it's not dynamically possible from the perspective of Hugo to show pages that are not generated.

It's possible to do that but we should implement some FE logic that will load the data from BCMS dynamically if the preview=1 is defined. Still, it's a different approach from the patterns of static site-generated content.

I guess that we discuss the problem here: https://github.com/ButterCMS/gatsbyjs-starter-buttercms/issues/31#issuecomment-1022301693 Take a look at that issue and let us now if it's ok for you.

**Comment by ViolanteCodes** [comment]
@prokopsimek 
> I guess that we discuss the problem here: [ButterCMS/gatsbyjs-starter-buttercms#31 (comment)](https://github.com/ButterCMS/gatsbyjs-starter-buttercms/issues/31#issuecomment-1022301693) Take a look at that issue and let us now if it's ok for you.

By "let us know if it's okay for you," do you mean, "let us know if we can implement the same method as a fix?" Or did you mean something else?

Thanks!

**Comment by prokopsimek** [comment]
> @prokopsimek
> 
> > I guess that we discuss the problem here: [ButterCMS/gatsbyjs-starter-buttercms#31 (comment)](https://github.com/ButterCMS/gatsbyjs-starter-buttercms/issues/31#issuecomment-1022301693) Take a look at that issue and let us now if it's ok for you.
> 
> By "let us know if it's okay for you," do you mean, "let us know if we can implement the same method as a fix?" Or did you mean something else?
> 
> Thanks!

It means "let me know if you want the same behavior as is in the GatsbyJS project" - it means that the user has to define the preview URL for an environment where content is generated with env prview=true to see all preview data.

**Comment by ViolanteCodes** [comment]
@prokopsimek 
> It means "let me know if you want the same behavior as is in the GatsbyJS project" - it means that the user has to define the preview URL for an environment where content is generated with env prview=true to see all preview data.

I'm assuming the answer is yes, if possible-- @jakelumetta can you weigh in on this one?

**Pull request merged**
